import json
import os
import sys
import numpy as np
from solver.engine import MegaSolver
from solver.laws import geometric, tiling, motion, recoloring, symmetry, logic, filling, stamping, topology

def get_all_laws():
    return [
        topology.solve_extract_shape_that_scales_to_another,
        filling.solve_diagonal_propagation_from_seeds_by_region_color,
        stamping.solve_replicate_shape_in_matching_quadrant_pockets,
        recoloring.solve_recolor_vertical_segments_half_split,
        topology.solve_extract_dense_3x3_with_max_target_color,
        filling.solve_inside_projection_with_diagonals,
        recoloring.solve_recolor_shape_to_target_color,
        geometric.solve_geometric,
        geometric.solve_diagonal_periodicity_completion,
        filling.solve_draw_frames_and_beams_from_maroon_blocks,
        recoloring.solve_recolor_by_column_index_parity_relative_to_width,
        filling.solve_fill_cross_corridors_between_clusters,
        geometric.solve_generate_alternating_triangle_from_vertical_line,
        recoloring.solve_recolor_by_orthogonal_adjacency_rule,
        motion.solve_move_pixels_to_matching_frame_edge,
        stamping.solve_map_unique_color_to_3x3_pattern,
        geometric.solve_concentric_voronoi_by_parity,
        tiling.solve_replicate_row_sequence_downwards,
        logic.solve_logical_or_of_3x3_corners,
        geometric.solve_generate_triangle_from_row_count,
        filling.solve_restore_interrupted_lines,
        geometric.solve_pixel_upscaling_by_unique_colors_count,
        filling.solve_checkerboard_flood_fill_around_obstacles,
        recoloring.solve_recolor_blobs_by_size_min_vs_others,
        symmetry.solve_mirror_pattern_by_2x2_junction,
        motion.solve_stack_row_segments_by_length_right_aligned,
        recoloring.solve_recolor_components_by_path_topology,
        geometric.solve_propagate_diagonal_line_relative_to_5s,
        filling.solve_fill_gaps_between_supported_runs,
        filling.solve_project_seeds_to_nearest_perpendicular_lines,
        filling.solve_cast_rays_from_source_through_internal_corners,
        tiling.solve_vertical_oscillating_mirror_tiling,
        geometric.solve_draw_diagonals_from_pixel_0,
        recoloring.solve_rows_to_checkerboard,
        topology.solve_overlay_bottom_on_top_by_divider,
        filling.solve_draw_cross_at_midpoint_of_color_1,
        motion.solve_propagate_shape_along_ray,
        recoloring.solve_recolor_pockets_by_size,
        stamping.solve_replicate_template_at_markers,
        filling.solve_fill_enclosed_rectangular_pockets,
        stamping.solve_stamp_template_on_canvas_by_anchors,
        topology.solve_extract_max_count_region,
        stamping.solve_replicate_red_seed_at_matched_local_envs,
        motion.solve_shift_cross_to_new_intersection,
        symmetry.solve_rotational_symmetry_completion,
        symmetry.solve_mirror_half_across_divider,
        recoloring.solve_recolor_strips_by_majority,
        geometric.solve_propagate_color_along_modulo_grid,
        geometric.solve_triangle_wave_pixel_propagation,
        topology.solve_extract_major_color_bbox_1x1,
        motion.solve_move_color_towards_target_color,
        topology.solve_extract_rotated_region_by_color_3,
        topology.solve_extract_most_populated_column,
        filling.solve_reflected_rays_from_source_through_lens,
        recoloring.solve_shift_and_recolor_pixels,
        stamping.solve_fill_object_holes_with_matched_patterns,
        stamping.solve_scaled_template_stamping_at_markers,
        filling.solve_fill_reachable_zeros_from_color_1,
        geometric.solve_template_periodicity,
        stamping.solve_stamp_missing_bg_pattern,
        filling.solve_red_cross_at_variable_scale,
        filling.solve_extend_towards_static_object,
        filling.solve_fill_frame_and_cast_rays_through_gaps,
        filling.solve_fill_enclosed_holes_with_color_3,
        filling.solve_fill_box_between_two_objects,
        filling.solve_connect_same_color_orthogonal_with_8,
        filling.solve_fill_horizontal_gap_between_1s,
        filling.solve_greedy_fill_maximal_rectangles,
        filling.solve_draw_cross_at_anchor_by_particles,
        filling.solve_fill_rectangles_by_corners,
        filling.solve_projection_from_protrusions,
        filling.solve_mirror_5_over_2,
        filling.solve_vanishing_point_slope_fill,
        filling.solve_fill_closed_open_regions,
        filling.solve_extend_rays_from_2x2_core,
        filling.solve_denoise_and_fill_holes,
        filling.solve_frame_and_gray_bridges,
        stamping.solve_seed_pattern_inference,
        stamping.solve_tile_pieces_to_template,
        stamping.solve_draw_3x3_hollow_squares_at_markers,
        stamping.solve_alternating_shape_stamping_h,
        stamping.solve_grid_intersection_quad_to_3x3,
        stamping.solve_count_blue_to_red_pattern_3x3,
        stamping.solve_pattern_expansion_by_key_quadrants,
        stamping.solve_replicate_blue_by_yellow_isometry,
        stamping.solve_skeleton_stamp_composition,
        stamping.solve_tile_pattern_to_fill_zeros,
        topology.solve_extract_smallest_color_bbox,
        topology.solve_count_pixels_to_horizontal_bar,
        topology.solve_extract_most_scattered_color_pixel,
        topology.solve_extract_symmetric_object,
        topology.solve_extract_hollow_rect_with_dots,
        topology.solve_quadrant_priority_overlap_by_cross,
        topology.solve_extract_non1_bbox_with_mask,
        topology.solve_extract_unique_3x3_pattern,
        topology.solve_extract_fliplr_bbox,
        topology.solve_quadrant_priority_overlap_4x4,
        topology.solve_three_sections_priority_overlay_4x4,
        topology.solve_extract_inner_box_by_blue_lines,
        topology.solve_grid_cells_to_modal_color,
        topology.solve_extract_2x2_solid_blocks,
        topology.solve_count_1x2_blocks_to_nx1,
        topology.solve_2x2_blocks_to_3x3_pattern,
        recoloring.solve_recolor_template_by_gray_frame,
        recoloring.solve_recolor_pieces_by_column_marker,
        recoloring.solve_color_columns_by_5s_count,
        recoloring.solve_color_rows_relative_to_marker,
        recoloring.solve_recolor_rows_by_5s_column_index,
        recoloring.solve_recolor_isolated_pixels,
        symmetry.solve_reflect_azure_by_yellow_tip,
        symmetry.solve_5x5_mask_symmetric_vote,
        geometric.solve_pixel_upscaling_by_2x2,
        geometric.solve_draw_diagonal_lines_by_offset,
        geometric.solve_upscale_grid_by_nonzero_count,
        geometric.solve_tile_2x2_with_filled_cols,
        geometric.solve_radial_concentric_circles,
        geometric.solve_skew_vector_to_diagonal_matrix,
        geometric.solve_crosshair_transform_on_largest_rect,
        topology.solve_count_magenta_3x3_to_blue,
        recoloring.solve_recolor_5_by_local_1d_symmetry,
        topology.solve_fill_frames_and_shoot_beams,
        motion.solve_propagate_seeds_with_deflection,
        motion.solve_move_pixels_to_center_by_quadrant,
        motion.solve_propagate_vertical_lines_with_deflection,
        motion.solve_extend_l_shape_arrowheads,
        motion.solve_extend_downwards_by_color_count,
        topology.solve_extract_hole_and_draw_crosses,
        topology.solve_extract_major_region_with_seeds,
        stamping.solve_guide_and_shape_stamping,
        topology.solve_fill_cells_by_divider_gaps,
        recoloring.solve_propagate_first_row_pattern,
        stamping.solve_copy_stencil_to_empty_holes,
        geometric.solve_duplicate_pattern_to_marker,
        geometric.solve_subgrid_kronecker_self_product,
        topology.solve_crop_to_best_color1_object,
        topology.solve_fill_target_object_holes_with_2,
        tiling.solve_vertical_periodic_extension,
        topology.solve_rotate_regions_90_180,
        topology.solve_extract_line_colors_to_grid,
        filling.solve_fill_towards_edge_or_divider,
        geometric.solve_mirror_v_then_h_mirror_then_tile_3,
        recoloring.solve_fill_hollow_rects_by_parity,
        recoloring.solve_reverse_nested_rect_colors,
        geometric.solve_clear_lines_with_holes_by_orientation,
        geometric.solve_repeat_pixel_and_add_5s,
        topology.solve_subgrid_bbox,
        geometric.solve_shift_pixel_down_and_fill_checkerboard,
        recoloring.solve_recolor_hollow_rects,
        geometric.solve_meta_grid_kronecker_product,
        tiling.solve_modulo_tiling_around_central_object,
        stamping.solve_reflected_corner_stamping,
        topology.solve_project_colors_to_borders,
        motion.solve_complete_snake_path_with_color_1,
        symmetry.solve_reflected_dotted_lines_by_count,
        symmetry.solve_reflect_pixels_across_frame_edges,
        topology.solve_project_objects_to_borders,
        symmetry.solve_concentric_boxes_repeating_dots,
        geometric.solve_extend_horizontally_with_5,
        topology.solve_map_4x4_blocks_to_color,
        motion.solve_l_shape_extension_to_edge,
        filling.solve_fill_enclosed_zeros_with_1,
        topology.solve_fill_diagonal_cells_123,
        topology.solve_grid_cells_to_output_flipped,
        topology.solve_point_reflected_hole_region,
        recoloring.solve_colors_to_vertical_lines_by_count,
        logic.solve_4x4_xor_to_color_3,
        logic.solve_3x3_and_to_color_2,
        logic.solve_3x3_logical_or_to_color_6,
        motion.solve_flip_solid_rectangle_in_bbox,
        tiling.solve_extend_row_periodicity_horizontally,
        logic.solve_4x4_empty_overlap_to_color_2,
        stamping.solve_draw_dots_around_2x2_blocks,
        recoloring.solve_keep_largest_color_others_to_5,
        recoloring.solve_recolor_5_to_X_and_X_to_0,
        recoloring.solve_extract_top_3_colors_to_3x1,
        geometric.solve_pixel_upscaling_by_3x3,
        geometric.solve_draw_hollow_rect_between_anchors,
        topology.solve_extract_dynamic_grid_from_blocks,
        recoloring.solve_extend_color_8_with_color_1,
        stamping.solve_draw_3x3_frames_by_color_map,
        stamping.solve_repeat_3x3_stamps_based_on_pixel_count,
        topology.solve_extract_largest_solid_rectangle,
        geometric.solve_border_and_hole_fill,
        motion.solve_move_up_by_height,
        filling.solve_fill_lines_between_opposite_edges,
        topology.solve_subgrid_unique_marker_presence,
        topology.solve_fit_grey_to_nearest_hole,
        # topology.solve_fit_grey_to_holes_v2, # Moved to bottom due to potential hangs on tasks with many objects
        topology.solve_move_block_with_color_as_position,
        topology.solve_combine_two_objects_3x3,
        topology.solve_multicolor_pattern_masked_by_grid,
        topology.solve_subgrid_unique_pixel_presence,
        topology.solve_extract_unique_asymmetric_3x3_subgrid,
        topology.solve_largest_hollow_rect_color_2x2,
        recoloring.solve_complete_3x3_with_color,
        geometric.solve_hollow_with_8_if_enclosed,
        recoloring.solve_recolor_by_top_left_gray_frame_template,
        filling.solve_fill_largest_smallest_regions,
        filling.solve_fill_lines_between_opposite_edges,
        filling.solve_dual_red_line_azure_projection,
        filling.solve_intersection_3x3_yellow,
        filling.solve_fill_inner_rectangle_by_area_rank,
        filling.solve_fill_3x3_enclosures_with_blue,
        symmetry.solve_quadrant_mirroring_around_pivot,
        geometric.solve_scaled_object_with_rays,
        geometric.solve_mirrored_seed_by_divider,
        symmetry.solve_point_reflection_around_pivot,
        geometric.solve_vertical_mirror_concatenation,
        topology.solve_dominant_sequence_extraction,
        geometric.solve_expand_pixels_to_edges,
        symmetry.solve_quadrant_mirroring_around_2x2,
        topology.solve_extract_closest_object_bbox_3x3,
        stamping.solve_stamping_4x4_blocks,
        geometric.solve_scaled_pixel_with_diagonals,
        geometric.solve_rotational_tiling_2x2,
        filling.solve_fill_gaps_in_active_rows_cols,
        geometric.solve_diagonal_4x4_blocks,
        topology.solve_classify_3x3_to_1x1,
        filling.solve_fill_square_holes,
        stamping.solve_scaled_stamping_by_marker_size,
        filling.solve_seed_fill_in_blue_frames,
        geometric.solve_hollow_rectangles,
        geometric.solve_denoise_isolated_pixels,
        filling.solve_fill_gap_with_new_color,
        filling.solve_line_between_identical_points,
        filling.solve_cross_at_object_centers,
        filling.solve_fill_gap_with_new_color,
        motion.solve_project_markers_to_largest_block_v2,
        stamping.solve_quadrant_reflected_stamping,
        recoloring.solve_checkerboard_propagation,
        stamping.solve_template_stamping_to_containers,
        filling.solve_pixel_projection_to_blobs,
        motion.solve_steered_pathfinding,
        motion.solve_move_to_last_row_of_color,
        motion.solve_move_objects_into_containers,
        motion.solve_project_rays_from_object_to_anchors,
        motion.solve_extend_seeds_below_arrowhead,
        motion.solve_extend_red_crosses_with_azure,
        filling.solve_midpoint_filling,
        filling.solve_fill_empty_gap_between_nonzeros,
        logic.solve_spiral_ca,
        recoloring.solve_recolor_alternating_lines,
        recoloring.solve_partition_2x2_3x1,
        recoloring.solve_object_recolor_by_parity,
        topology.solve_diagonal_identity_by_object_count,
        tiling.solve_row_wise_periodic_shift,
        topology.solve_color_by_max_object_size,
        topology.solve_assemble_2x2_corners,
        topology.solve_marker_offset_composition,
        topology.solve_u_shape_hollow_empty_rows,
        filling.solve_enclosure_fill,
        filling.solve_enclosure_fill_v2,
        filling.solve_flood_fill_partitioned_grid,
        topology.solve_grid_cell_count,
        geometric.solve_kronecker,
        geometric.solve_scaling,
        geometric.solve_pixel_upscaling_by_factor,
        geometric.solve_translation,
        geometric.solve_denoising,
        geometric.solve_denoise_by_symmetry,
        geometric.solve_object_wise_kronecker,
        geometric.solve_template_kronecker,
        geometric.solve_anchor_template_matching,
        geometric.solve_duplicate_object_horizontally,
        geometric.solve_trigger_kronecker,
        geometric.solve_stretch_to_marker,
        geometric.solve_meeting_hooks,
        geometric.solve_cross_with_intersection_recolor,
        tiling.solve_simple_tiling,
        tiling.solve_grid_sync,
        tiling.solve_horizontal_tiling_by_period,
        tiling.solve_tiled_checkerboard,
        tiling.solve_tiled_xor_parity,
        tiling.solve_row_periodicity_extension,
        tiling.solve_row_periodicity_extension_v2,
        tiling.solve_diagonal_staircase_extension,
        tiling.solve_row_wise_periodic_shift,
        tiling.solve_first_tiled_block,
        tiling.solve_local_periodic_completion,
        tiling.solve_pattern_extension_1d,
        tiling.solve_tiled_with_background_pattern,
        tiling.solve_global_stencil_tiling,
        tiling.solve_global_shape_union_to_subgrids,
        tiling.solve_copy_row_by_marker_column,
        tiling.solve_reflective_periodic_extraction,
        tiling.solve_tiled_with_diagonal_markers,
        tiling.solve_grid_cell_template_growth,
        motion.solve_targeted_gravity,
        motion.solve_targeted_horizontal_move,
        motion.solve_row_wise_motion,
        motion.solve_pixel_gravity_independent,
        motion.solve_object_gravity_pixel_wise,
        motion.solve_bounce_diagonal_from_middle,
        motion.solve_global_x_rays,
        motion.solve_object_move_by_marker_color,
        motion.solve_object_move_to_marker_center,
        motion.solve_move_to_bbox_proximity,
        motion.solve_project_pixels_to_block,
        motion.solve_ray_from_marker_on_bbox_edge,
        motion.solve_column_gravity_fill,
        motion.solve_diagonal_ray_expansion,
        motion.solve_reflected_diagonal_rays,
        motion.solve_diagonal_down_right_propagation,
        motion.solve_object_symmetry,
        motion.solve_object_gravity_with_obstacles,
        motion.solve_object_move_to_marker,
        motion.solve_object_gravity_with_wrap,
        motion.solve_deskew_by_one_step,
        motion.solve_diagonal_propagation_from_marker,
        motion.solve_blob_perpendicular_reflection,
        motion.solve_move_to_adjacent_line,
        motion.solve_align_objects_to_anchor,
        motion.solve_single_pixel_projection,
        recoloring.solve_checkered_recolor,
        recoloring.solve_3x3_periodic_recolor,
        recoloring.solve_periodic_recolor_3x3,
        recoloring.solve_recolor_to_nearest_full_line,
        recoloring.solve_recolor_by_size_order,
        recoloring.solve_recolor_enclosing_components,
        recoloring.solve_recolor_to_frame,
        recoloring.solve_recolor_main_in_red_bbox_no_bg,
        recoloring.solve_swap_colors_in_bounding_box,
        recoloring.solve_recolor_in_bounding_box,
        recoloring.solve_recolor_min_max_objects,
        recoloring.solve_row_wise_recolor_from_source,
        recoloring.solve_object_recolor_by_size,
        recoloring.solve_recolor_by_size_rank,
        recoloring.solve_recolor_by_area_rank,
        recoloring.solve_recolor_diagonal_alternating,
        recoloring.solve_recolor_by_feature,
        recoloring.solve_concentric_recolor,
        recoloring.solve_object_recolor_by_relative_position,
        symmetry.solve_global_symmetry_completion,
        symmetry.solve_4fold_with_2fold_frame,
        symmetry.solve_reflection_by_adjacent_symmetry,
        symmetry.solve_reflection_by_dominant_axis,
        symmetry.solve_reflection_by_axis,
        symmetry.solve_global_reflection_with_c1_priority,
        symmetry.solve_reflection_completion,
        symmetry.solve_reflection_duplication,
        symmetry.solve_marker_midpoint_reflection,
        symmetry.solve_ray_symmetry_fixed,
        symmetry.solve_grid_rotation_completion,
        symmetry.solve_object_symmetry_completion,
        symmetry.solve_seed_symmetry_expansion,
        logic.solve_mask_intersection,
        logic.solve_logical_or_recolor,
        logic.solve_subgrid_logical_ops,
        logic.solve_path_existence_between_blocks,
        recoloring.solve_color_by_count,
        logic.solve_global_logical_op,
        logic.solve_cross_intersection_swap,
        filling.solve_grid_fill_between_points,
        filling.solve_connect_points_l_shape,
        filling.solve_bouncing_sequence,
        filling.solve_fill_empty_row_col,
        filling.solve_grid_fill_gaps,
        filling.solve_stepped_zigzag_expansion,
        filling.solve_horizontal_gap_fill,
        filling.solve_row_uniformity_check,
        filling.solve_max_seed_count_filling,
        filling.solve_region_frame_expansion,
        filling.solve_marker_box_3x3,
        filling.solve_row_col_consistency_propagation,
        filling.solve_grid_connect_identical_blocks,
        filling.solve_master_cell_dynamic_map,
        filling.solve_cross_expansion_fixed_5x5,
        filling.solve_color_line_expansion,
        filling.solve_line_intersection_expansion,
        filling.solve_bar_pivot_extension,
        filling.solve_maze_path_alternating_color,
        filling.solve_lines_by_color,
        filling.solve_connect_diagonal_pairs,
        filling.solve_connect_same_color_orthogonal_pairs,
        stamping.solve_3x3_stamp_at_markers,
        stamping.solve_object_template_replace,
        stamping.solve_pattern_substitution,
        stamping.solve_marker_pattern_stamping,
        stamping.solve_marker_pattern_recoloring,
        stamping.solve_marker_pattern_extension,
        stamping.solve_fill_gaps_between_rectangular_bounds,
        stamping.solve_marker_neighborhood_union,
        stamping.solve_move_objects_into_matching_holes,
        stamping.solve_template_stamping_by_shared_color,
        stamping.solve_marker_3x3_stamping,
        stamping.solve_clean_stamping,
        stamping.solve_isometric_stamping,
        stamping.solve_frame_around_multi_pixel_components,
        stamping.solve_connected_reflective_stamping,
        stamping.solve_connect_meta_objects,
        stamping.solve_skeleton_template_rotation,
        stamping.solve_expand_shape_by_cross_template,
        topology.solve_subgrid_uniqueness,
        topology.solve_subgrid_by_square_frame,
        topology.solve_snake_sort_by_column,
        topology.solve_extract_smallest_bbox_object,
        topology.solve_extract_quadrant,
        topology.solve_subgrid_by_unique_color,
        topology.solve_subgrid_unique_content,
        topology.solve_subgrid_inside_frame,
        topology.solve_count_blobs_as_grid,
        topology.solve_largest_subgrid_extraction,
        topology.solve_object_extraction,
        topology.solve_recursive_subgrid,
        topology.solve_container_payload_matching,
        topology.solve_most_frequent_3x3_object,
        logic.solve_ca,
        # New laws added in this session (at the bottom to avoid regressions)
        recoloring.solve_checkerboard_propagation,
        recoloring.solve_block_alternating_zero,
        symmetry.solve_double_reflection,
        stamping.solve_meta_grid_template_stamping,
        stamping.solve_seed_pattern_replication,
        stamping.solve_marker_bounded_extraction,
        filling.solve_corner_completion_2x2,
        filling.solve_largest_common_gap,
        filling.solve_concentric_frames,
        stamping.solve_marker_seed_copy,
        stamping.solve_stamp_template_at_markers_v2,
        stamping.solve_marker_scaling_stamping,
        stamping.solve_upscale_seed_to_fit_hollow_rect,
        stamping.solve_replace_hollow_with_plus,
        motion.solve_push_to_block_with_stacking,
        topology.solve_concentric_assembly,
        topology.solve_largest_hollow_rect_color_2x2,
        recoloring.solve_recolor_gray_by_red_presence,
        motion.solve_bouncing_diagonal,
        recoloring.solve_recolor_seed_by_frame_distance,
        recoloring.solve_intra_input_template_completion,
        # NEW LAWS
        geometric.solve_diagonal_extension_by_color,
        recoloring.solve_place_5_on_diagonal,
        recoloring.solve_fill_modal_value,
        recoloring.solve_partitioned_grid_dominant_color_mapping,
        geometric.solve_draw_8_border,
        topology.solve_extract_top_right_3x3,
        topology.solve_extract_3x3_from_blocked_grid,
        topology.solve_extract_shape_with_marker_bbox,
        motion.solve_drop_marker_below_opening,
        symmetry.solve_move_shape_to_divider,
        filling.solve_flood_fill_partitioned_grid,
        filling.solve_fill_rectangle_from_two_points,
        topology.solve_crop_between_fences,
        topology.solve_extract_3x3_structure_from_divisible_bbox,
        geometric.solve_concentric_frame_intersection,
        # POTENTIAL HANG: This law can be very slow if there are many objects and holes.
        geometric.solve_border_and_hole_fill,
        geometric.solve_concentric_repeating_shells,
        motion.solve_block_move_one_step_on_path,
        topology.solve_fit_grey_to_holes_v2,
        stamping.solve_shape_replication_by_maximal_template,
        recoloring.solve_fill_if_not_between_same_color,
        filling.solve_red_cross_at_variable_scale
    ]

def main(training_dir, target_file=None):
    if target_file:
        if not target_file.endswith('.json'): target_file += '.json'
        files = [target_file]
    else:
        files = sorted([f for f in os.listdir(training_dir) if f.endswith('.json')])
    
    laws = get_all_laws()
    solved_count = 0
    print(f"MODULAR MEGA SOLVER STARTING. Targets: {len(files)}")
    
    for f in files:
        f_path = os.path.join(training_dir, f)
        if not os.path.exists(f_path):
            print(f"File not found: {f_path}")
            continue
        with open(f_path) as jf:
            data = json.load(jf)
        
        solver = MegaSolver(data)
        for law in laws:
            solver.register_method(law)
            
        preds, name = solver.brute_force()
        if preds:
            actual_test_outs = [np.array(x['output']) for x in data['test']]
            all_match = True
            for i, (p, a) in enumerate(zip(preds, actual_test_outs)):
                if p is None or p.shape != a.shape or not np.array_equal(p, a):
                    all_match = False
                    print(f"--- FAILED TEST CASE {i} ---")
                    if p is None:
                        print("Predicted: None")
                    else:
                        print(f"Predicted shape: {p.shape}, Actual shape: {a.shape}")
                        if p.shape == a.shape:
                            diff = p != a
                            print(f"Number of differing pixels: {np.sum(diff)}")
                        print("PREDICTED:")
                        print(p)
                    print("ACTUAL:")
                    print(a)
                    break

            if all_match:
                print(f"✅ VERIFIED SOLVE: {f} :: {name}")
                solved_count += 1
            else:
                print(f"❌ FAILED VERIFICATION: {f} :: {name}")
        else:
            print(f"❌ NOT SOLVED: {f}")
            
    print(f"\nFINAL VERIFIED SCORE: {solved_count} / {len(files)}")

if __name__ == "__main__":
    training_dir = "Arc-1/training"
    target = None
    if len(sys.argv) > 1:
        target = sys.argv[1]
    if len(sys.argv) > 2:
        training_dir = sys.argv[2]
    
    main(training_dir, target)
